language: python
dist: xenial
python:
  - "3.7"

sudo: false

stages:
  - test
  - bundle
  - name: deploy
    if: tag =~ /^v\d+\.\d+\.\d+$/ AND repo = HaaLeo/bug-prediction

install:
  - pip install pipenv
  - pipenv sync --dev

jobs:
  include:
    - stage: test
      script:
        - python -m pylint ./*/*.py
        - python -m pytest --cov bugprediction bugprediction_test
    - stage: bundle
      script:
        - python setup.py sdist bdist_wheel
    - stage: deploy
      before_deploy:
        - python setup.py sdist bdist_wheel
        - twine upload dist/* -u HaaLeo -p ${PYPI_PASSWORD}
      script: skip
      deploy:
        provider: releases
        file_glob: true
        file: "dist/*"
        api_key: ${TRAVIS_CD}
        skip_cleanup: true
        on:
          tags: true

after_success:
  - codecov
